# https://taskfile.dev/docs/guide
# https://taskfile.dev/reference/templating/
version: '3'
tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix
  fmt: mix format

  rel: mix hex.publish
  doc: mix docs

  ecto.create.code: |
    wget https://raw.githubusercontent.com/elixir-ecto/ecto/refs/tags/v3.14.2/lib/mix/tasks/ecto.create.ex

  setup: |
    mix deps.get
